model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModel
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    n_embed: 256
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.75
        codebook_weight: 1.0

    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 256
      in_channels: 1
      tanh_out: true
      out_ch: 1
      ch: 32
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    max_epochs: 1
    benchmark: True
    accumulate_grad_batches: 2
